on: [ push ]

name: Cargo Build and Test

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install build dependencies
        run: sudo apt install libx11-dev libxtst-dev libudev-dev libinput-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
